# Generated by Django 3.0.2 on 2020-01-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200125_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoir',
            name='trip_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
