# Generated by Django 3.0.2 on 2020-01-25 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20200125_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoir',
            name='branch',
            field=models.CharField(default='Enforcement branch', max_length=50),
        ),
        migrations.AlterField(
            model_name='hoir',
            name='occurence_date_hazard',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Oscr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(blank=True, max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('verbal_threat', models.BooleanField(blank=True)),
                ('weapons_nearby', models.BooleanField(blank=True)),
                ('physical_contact', models.BooleanField(blank=True)),
                ('assault', models.BooleanField(blank=True)),
                ('damage_equipment', models.BooleanField(blank=True)),
                ('other_risk_specify', models.TextField(blank=True, max_length=200)),
                ('industrial_facility', models.BooleanField(blank=True)),
                ('commercial_facility', models.BooleanField(blank=True)),
                ('remote_location', models.BooleanField(blank=True)),
                ('agriculture', models.BooleanField(blank=True)),
                ('marine', models.BooleanField(blank=True)),
                ('first_nations', models.BooleanField(blank=True)),
                ('isolated', models.BooleanField(blank=True)),
                ('other_riskloc_specify', models.TextField(blank=True, max_length=200)),
                ('inspections', models.BooleanField(blank=True)),
                ('witness_statements', models.BooleanField(blank=True)),
                ('court_docs', models.BooleanField(blank=True)),
                ('warrant', models.BooleanField(blank=True)),
                ('surveillance', models.BooleanField(blank=True)),
                ('other_duty_specify', models.TextField(blank=True, max_length=200)),
                ('fisheries_act', models.BooleanField(blank=True)),
                ('name_reg1', models.TextField(blank=True, max_length=200)),
                ('cepa_1999', models.BooleanField(blank=True)),
                ('name_reg2', models.TextField(blank=True, max_length=200)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('years_experience', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('branch', models.CharField(default='Enforcement branch', max_length=50)),
                ('gavia_num', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=150)),
                ('occurence_date_hazard', models.DateTimeField()),
                ('occurence_description', models.TextField(max_length=800)),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oscrs',
            },
        ),
    ]
