# Generated by Django 2.2.5 on 2020-01-26 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20200125_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closeout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(blank=True, max_length=200)),
                ('close_remarks', models.TextField(max_length=800)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'closeouts',
            },
        ),
    ]
