# Generated by Django 3.0.2 on 2020-01-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_closeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoir',
            name='mail_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hoir',
            name='other_inj',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hoir',
            name='work_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='office',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dest_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='purpose_other',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
