# Generated by Django 3.0.2 on 2020-01-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200131_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='city',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='office',
            name='postal_code',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='office',
            name='province',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='office',
            name='region',
            field=models.CharField(max_length=200),
        ),
    ]
