# Generated by Django 3.0.2 on 2020-02-01 14:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200131_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
