# Generated by Django 3.0.2 on 2020-02-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200207_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='dest_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dest_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
