# Generated by Django 3.0.3 on 2020-02-09 11:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200207_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='dest_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
